export const LAT_LNG_SELECTED = 'LAT_LNG_SELECTED';
export const DIRECTIONS_READY = 'DIRECTIONS_READY';

export const UNDO = 'UNDO';

export const POI_SELECTED = 'POI_SELECTED';
export const POI_DESELECTED = 'POI_DESELECTED';
export const POI_ADDED_TO_ROUTE = 'POI_ADDED_TO_ROUTE';
