export const LAT_LNG_SELECTED = 'LAT_LNG_SELECTED';
export const DIRECTIONS_READY = 'DIRECTIONS_READY';

export const ELEVATIONS_UPDATED = 'ELEVATIONS_UPDATED';

export const UNDO = 'UNDO';

export const POI_SELECTED = 'POI_SELECTED';
export const POI_DESELECTED = 'POI_DESELECTED';
export const POI_ADDED_TO_ROUTE = 'POI_ADDED_TO_ROUTE';

export const SAMPLE_RATE = 100;

export const MAP_BOOTED = 'MAP_BOOTED';

export const PLACE_LOOKUP_STARTED = 'PLACE_LOOKUP_STARTED';
export const PLACE_LOOKUP_FINISHED = 'PLACE_LOOKUP_FINISHED';
